import Boost.Python

class Error(Boost.Python.enum):
    EvaluationError: Any = ...
    IncompatibleMode: Any = ...
    MissingLocation: Any = ...
    MissingRegion: Any = ...
    NoError: Any = ...
    Null: Any = ...
    SyntaxError: Any = ...
    UnsupportedFeature: Any = ...
    names: Any = ...
    values: Any = ...
    __slots__: Any = ...

class Mode(Boost.Python.enum):
    IntervalMode: Any = ...
    PointInTimeMode: Any = ...
    names: Any = ...
    values: Any = ...
    __slots__: Any = ...

class Modes(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class OpeningHours(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def error(KOpeningHours) -> Any: ...
    @classmethod
    def normalizedExpression(KOpeningHours) -> Any: ...
    @classmethod
    def setExpression(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
